---
title: "Iris_lda"
author: "徐宁"
date: "2018/12/12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown



```{r }
library(MASS)
library(ROCR)
library(e1071)
library(ggplot2)
```
截图两个种类花的数据，做出散点图观察数据分布

```{r}
iris2=iris[-which(iris$Species=='virginica'),3:5]
iris2$Species=factor(iris2$Species)
ggplot(data=iris2)+
  geom_point(aes(Petal.Length,Petal.Width,color=Species,shape=Species))

```
线性分类器的功能是找出一个标准，在数据的分布中将类型划分开，为了进行验证，将数据集分成两组train和test分别用于训练充当分类器的模型的数据和用于检验的数据
```{r}
s=sample(1:nrow(iris2),nrow(iris2)*0.7)
train=iris2[s,]
test=iris2[-s,]
```
下一步，使用MASS包里的线性分类函数做出分类模型
```{r}
classifier=lda(Species~Petal.Length+Petal.Width,data=train)
```
进一步，看模型对测试数据集test分类是否正确
```{r}
y_pred=predict(classifier,type='response',newdata = test)
table(test$Species,y_pred$class)
```
```{r}
s=sample(1:nrow(iris),nrow(iris)*0.7)
train1=iris[s,]
test1=iris[-s,]
```

利用svm对train1进行分类训练，标签变量Species
```{r}
classifier1=svm(Species~.,data=train1,type='C-classification',kernel='linear')
y_pred1=predict(classifier1,newdata = test1)
```
用混淆矩阵检验分类精确性
```{r}
table(test1$Species,y_pred1)
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
